// ---------------------------------------------------------------------------
// Product Domain Entities — maps 1:1 to Sanity "saree" document schema
// ---------------------------------------------------------------------------

/** Sanity image asset reference with optional hotspot/crop and LQIP metadata */
export interface ISanityImage {
  _type: "image";
  asset: {
    _ref: string;
    _type: "reference";
  };
  hotspot?: {
    x: number;
    y: number;
    height: number;
    width: number;
  };
  crop?: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
  alt?: string;
  /** Base64-encoded Low-Quality Image Placeholder generated by Sanity */
  lqip?: string;
  /** Resolved URL — populated after GROQ projection */
  url?: string;
}

/** Union of product categories used for filtering and routing */
export type ProductCategory = "Silk" | "Cotton" | "Heritage";

/** Badge labels surfaced on product cards */
export type ProductBadge = "Limited Edition" | "New" | "Bestseller" | "Heritage";

/** Weave/sub-collection for detailed classification */
export type WeaveType =
  | "Kanjeevaram"
  | "Banarasi"
  | "Chanderi"
  | "Raw Silk"
  | "Tussar"
  | "Handloom"
  | "Khadi"
  | "Jamdani"
  | "Chettinad"
  | "Linen Blend"
  | "Patola"
  | "Paithani"
  | "Bridal"
  | "Bespoke";

/** Individual product variant — each has its own SKU, price, and stock */
export interface IProductVariant {
  _key: string;
  sku: string;
  color: string;
  /** Hex value for swatch rendering */
  colorHex: string;
  size?: string;
  price: number;
  compareAtPrice?: number;
  stockQuantity: number;
  /** Variant-specific image, falls back to product mainImage if absent */
  image?: ISanityImage;
}

/** Full product entity — the core domain model */
export interface IProduct {
  /** Sanity document _id */
  _id: string;
  _type: "saree";
  _createdAt: string;
  _updatedAt: string;

  title: string;
  slug: {
    _type: "slug";
    current: string;
  };
  description: string;

  category: ProductCategory;
  weaveType: WeaveType;
  collection: string;

  mainImage: ISanityImage;
  /** Additional gallery images for the PDP */
  imageGallery: ISanityImage[];
  /** Hover image for product cards (resolved URL) */
  hoverImage?: ISanityImage;

  /** Variants with independent SKU, pricing, and stock */
  variants: IProductVariant[];

  /** Base price — lowest variant price or standalone price */
  price: number;
  compareAtPrice?: number;

  /** Palette hex values for card swatches (derived from variants or manual) */
  palette: string[];

  badge?: ProductBadge;

  /** SEO metadata pulled for generateMetadata */
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: ISanityImage;
  };
}

/** Lightweight product summary for listings — avoids fetching full gallery */
export interface IProductCard
  extends Pick<
    IProduct,
    | "_id"
    | "title"
    | "slug"
    | "category"
    | "collection"
    | "price"
    | "compareAtPrice"
    | "badge"
    | "palette"
    | "description"
  > {
  mainImageUrl: string;
  mainImageLqip?: string;
  hoverImageUrl?: string;
}
